// Scale-tier benchmark: 100 / 1,000 / 10,000 workers, CSV import + full-month roster generation,
// staged timing report. See the v4 design doc, Part C, "Scale-tier benchmarks: 100 / 1,000 /
// 10,000 workers, CSV import + full-month generation, staged timing report".
//
// This drives the real service layer DIRECTLY (in-process, real Postgres, real transactions, a
// real spawned Python solver subprocess), never through HTTP/pg-boss -- the design doc is explicit
// that precise internal-stage timing needs to see each internal `await`, which only the direct
// caller can do, and that this benchmark should NOT add permanent timing instrumentation to
// `CsvImportService`/`RosterGenerationService` themselves. Run with:
//
//   cd apps/api && npx tsx loadtest/scaleTiers.ts [tier ...]
//
// e.g. `npx tsx loadtest/scaleTiers.ts 100 1000` to run only a subset (useful for a quick smoke
// test before committing to the full, much slower 10,000-worker tier). Tiers always run smallest
// first regardless of the order given on the command line, per the design doc's "catch a problem
// at a small tier before burning time on the largest" reasoning.
//
// Requires: `docker-compose.dev.yml`'s Postgres up (DATABASE_URL in the repo-root `.env`), and
// `solver/.venv` (see `solver/README.md`) for the roster-generation stage's real CP-SAT solve --
// if the venv is missing, the CSV-import stage still runs and is reported; the roster-generation
// stage is skipped for every tier with a clear console warning instead of silently fabricating
// numbers for a solver that was never actually invoked.

import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { performance } from 'node:perf_hooks';

import { config as loadDotenv } from 'dotenv';
import { isValidIsraeliId, ROLES, SHIFT_TYPES } from '@rostering/shared';
import type { Role, ShiftType } from '@rostering/shared';

import { createPrismaClient, type PrismaClient } from '../src/db/client.js';
import { createBoss } from '../src/jobs/queue.js';
import { CsvImportService } from '../src/services/csvImportService.js';
import { RosterGenerationService, type SolveFn } from '../src/services/rosterGenerationService.js';
import { monthDays } from '../src/engine/calendar.js';
import { buildProblem, type EngineAvailabilityRow } from '../src/engine/problem.js';
import { runSolver, type RunSolverOptions } from '../src/engine/runSolver.js';
import { serializeWorkersCsv, type CsvWorkerRecord } from '../src/csv/index.js';

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(currentDir, '../../..');

loadDotenv({ path: path.resolve(REPO_ROOT, '.env') });

// ---------------------------------------------------------------------------------------------
// Tunables (kept as constants near the top per the design doc's explicit "keep this ratio a
// script parameter, not a hardcoded constant buried in logic" ask).
// ---------------------------------------------------------------------------------------------

/** 100 / 1,000 / 10,000 -- 10,000 is not an arbitrary round number, it is exactly `MAX_ROWS`
 * (confirmed in `apps/api/src/routes/importExport.ts`: `const MAX_ROWS = 10_000;`), so that tier
 * is specifically "does the system behave correctly and reasonably fast at its own documented
 * limit." Can be overridden via CLI args, e.g. `tsx loadtest/scaleTiers.ts 100 1000`. */
const ALL_TIERS = [100, 1000, 10_000] as const;

/** Share of each role's imported headcount that `StaffingRequirement.requiredCount` targets,
 * summed across the 3 shifts of a day -- design doc default suggestion ~40%. Deliberately a
 * runtime-configurable constant (env override), not hardcoded logic, since "the right utilization
 * to benchmark against is a judgment call worth being able to sweep." */
const UTILIZATION_RATIO = Number(process.env.LOADTEST_UTILIZATION_RATIO ?? 0.4);

/** Fixed, far-future month so this script's rosters never collide with anything a developer might
 * have generated by hand; also gives every tier a real 31-day month (harder problem than a 28-day
 * February) to solve. */
const TARGET_MONTH = '2030-01';

/** Node-side kill timeout `runSolver.ts` itself defaults to (`DEFAULT_TIMEOUT_MS`, not exported --
 * see that file), kept "slightly above the solver's own internal ~30s cap." Used here as the
 * pass/fail threshold for the 10,000-worker tier's solve stage, per the design doc's "use the
 * solver's documented ~30s internal cap plus your own Node-side spawn/IPC overhead as the
 * threshold" instruction. */
const SOLVE_REASONABLE_BOUND_MS = 35_000;

/** National-ID prefix range reserved for this script's synthetic workers -- high enough to never
 * collide with `db/seedData.ts`'s seed fixtures (prefixes 1-12) or
 * `e2e/support/dbAdminServer.ts`'s `bulkCreateWorkers` fixture range (500,000+, and on a wholly
 * separate E2E database in any case). Monotonically incremented across ALL tiers in one script
 * run (not reset per tier) since `Worker.nationalId` is globally unique. A random per-process
 * salt is folded in so re-running this script multiple times against the same persistent dev
 * Postgres (e.g. one tier at a time, across separate invocations, while iterating on this script)
 * doesn't collide with a PRIOR run's already-imported synthetic workers -- `globalWorkerCounter`
 * alone only guarantees uniqueness WITHIN one process. */
const NATIONAL_ID_BASE_PREFIX = 10_000_000 + Math.floor(Math.random() * 8_000_000);

/** Deterministic role mix for synthetic workers: roughly 60% GENERAL_GUARD / 20% SUPERVISOR / 20%
 * SCREENER, a plausible security-staffing skew (more guards than supervisors/screeners). */
const ROLE_PATTERN: readonly Role[] = [
  'GENERAL_GUARD', 'GENERAL_GUARD', 'GENERAL_GUARD',
  'SUPERVISOR',
  'SCREENER',
];

/** Deterministic per-worker availability-subset mix (same subset every day of the month, for
 * simplicity) -- NOT specified by the design doc's scale-tier text verbatim, but necessary for the
 * "solve" stage to be a meaningful benchmark at all: with zero `WorkerAvailability` rows, every
 * worker is unavailable every date (Availability v2's absence-is-unavailable rule), the solver's
 * candidate pool is empty, and "solve" would trivially return near-instantly regardless of worker
 * count -- which would silently defeat the entire point of this benchmark (the design doc's
 * explicit "solve is almost certainly the dominant cost at the top tier" question). Skewed toward
 * full availability (mirrors a workforce that mostly CAN work), with some 1-2-shift workers mixed
 * in for realistic constraint variety. See the tier report's notes for this explicit call-out. */
const AVAILABILITY_PATTERN: readonly string[] = ['ABC', 'ABC', 'ABC', 'ABC', 'AB', 'AB', 'BC', 'AC', 'A', 'C'];

const VENV_PYTHON = path.resolve(REPO_ROOT, 'solver/.venv/bin/python3');
const RESULTS_DIR = path.resolve(currentDir, 'results');

// ---------------------------------------------------------------------------------------------
// Synthetic data generation
// ---------------------------------------------------------------------------------------------

/** Adapted from `e2e/support/dbAdminServer.ts`'s `bulkCreateWorkers` -- same checksum-valid
 * synthetic-Israeli-national-ID algorithm (built there for a different purpose, probing the
 * availability-PUT payload-size limit, but the exact right tool here too), generalized to take an
 * arbitrary prefix rather than a hardcoded base. */
function checksumValidNationalId(prefix: number): string {
  const base = String(prefix).padStart(8, '0');
  for (let checkDigit = 0; checkDigit <= 9; checkDigit++) {
    const candidate = `${base}${checkDigit}`;
    let sum = 0;
    for (let d = 0; d < 9; d++) {
      const digit = Number(candidate[d]);
      const product = digit * (d % 2 === 0 ? 1 : 2);
      sum += product > 9 ? product - 9 : product;
    }
    if (sum % 10 === 0) {
      return candidate;
    }
  }
  throw new Error(`checksumValidNationalId: no valid check digit found for prefix ${prefix}`);
}

let globalWorkerCounter = 0;

/** Builds `count` synthetic worker+contract records with valid roles/status/checksum-valid
 * national IDs and reasonable hourly rates / monthly-hour bands. `globalWorkerCounter` is shared
 * across every tier in one script run so `nationalId` (globally unique across companies) never
 * collides between tiers. */
function buildSyntheticWorkerRecords(count: number): CsvWorkerRecord[] {
  const records: CsvWorkerRecord[] = [];
  for (let i = 0; i < count; i++) {
    const index = globalWorkerCounter++;
    const nationalId = checksumValidNationalId(NATIONAL_ID_BASE_PREFIX + index);
    if (!isValidIsraeliId(nationalId)) {
      // Defensive: would indicate the adapted checksum algorithm above has drifted from the real
      // validator -- fail loudly rather than silently importing an invalid ID.
      throw new Error(`buildSyntheticWorkerRecords: generated nationalId ${nationalId} fails isValidIsraeliId`);
    }
    const role = ROLE_PATTERN[index % ROLE_PATTERN.length] ?? 'GENERAL_GUARD';
    records.push({
      nationalId,
      name: `Load Test Worker ${index}`,
      role,
      status: 'ACTIVE',
      hourlyCostIls: 35 + (index % 40), // 35..74 ILS/hr
      minMonthlyHours: 0,
      maxMonthlyHours: 180 + (index % 40), // 180..219
    });
  }
  return records;
}

// ---------------------------------------------------------------------------------------------
// StaffingRequirement scaling ("inject the amount of people per shift")
// ---------------------------------------------------------------------------------------------

/** Splits `total` as evenly as possible across the 3 shifts, capping each shift's share at `cap`
 * -- "capped so it never exceeds the actual worker count in that role," per the design doc's
 * explicit reasoning: an unsatisfiable requirement just generates alerts, it doesn't stress the
 * solver's real assignment search; the point is to make the solve itself hard, not to manufacture
 * shortage alerts. */
function distributeAcrossShifts(total: number, cap: number): Record<ShiftType, number> {
  const base = Math.floor(total / SHIFT_TYPES.length);
  const remainder = total - base * SHIFT_TYPES.length;
  const result = {} as Record<ShiftType, number>;
  SHIFT_TYPES.forEach((shift, i) => {
    const raw = base + (i < remainder ? 1 : 0);
    result[shift] = Math.min(raw, cap);
  });
  return result;
}

/** Sets `requiredCount` per (role, shift) proportional to that role's share of the just-imported,
 * ACTIVE workforce -- the "utilization ratio" design from the v4 design doc's Part C. Returns the
 * per-role counts used, for the report. */
async function scaleStaffingRequirements(
  prisma: PrismaClient,
  companyId: number,
): Promise<Record<Role, number>> {
  const grouped = await prisma.worker.groupBy({
    by: ['role'],
    where: { companyId, status: 'ACTIVE' },
    _count: { _all: true },
  });
  const roleCounts = Object.fromEntries(ROLES.map((role) => [role, 0])) as Record<Role, number>;
  for (const row of grouped) {
    roleCounts[row.role] = row._count._all;
  }

  for (const role of ROLES) {
    const roleCount = roleCounts[role];
    const totalRequiredAcrossShifts = Math.round(roleCount * UTILIZATION_RATIO);
    const perShift = distributeAcrossShifts(totalRequiredAcrossShifts, roleCount);
    for (const shift of SHIFT_TYPES) {
      await prisma.staffingRequirement.upsert({
        where: { companyId_role_shift: { companyId, role, shift } },
        create: { companyId, role, shift, requiredCount: perShift[shift] },
        update: { requiredCount: perShift[shift] },
      });
    }
  }

  return roleCounts;
}

// ---------------------------------------------------------------------------------------------
// Availability seeding (benchmark setup only -- see AVAILABILITY_PATTERN's doc comment above for
// why this is necessary for the "solve" stage to be a meaningful measurement at all)
// ---------------------------------------------------------------------------------------------

async function seedAvailability(prisma: PrismaClient, companyId: number, month: string): Promise<number> {
  const workers = await prisma.worker.findMany({ where: { companyId }, select: { id: true } });
  const days = monthDays(month);
  const rows: { workerId: number; date: Date; shifts: string }[] = [];
  for (const worker of workers) {
    const pattern = AVAILABILITY_PATTERN[worker.id % AVAILABILITY_PATTERN.length] ?? 'ABC';
    for (const date of days) {
      rows.push({ workerId: worker.id, date: new Date(`${date}T00:00:00.000Z`), shifts: pattern });
    }
  }
  const CHUNK = 5000;
  for (let i = 0; i < rows.length; i += CHUNK) {
    await prisma.workerAvailability.createMany({ data: rows.slice(i, i + CHUNK) });
  }
  return rows.length;
}

// ---------------------------------------------------------------------------------------------
// Roster-generation stage timing
//
// `RosterGenerationService.generate()` is NOT split into separately-exported data-fetch /
// problem-build seams (only `buildProblem` and `runSolver` are independently importable; the
// worker/requirement/availability queries and `persistDraft` are private to the service). Per the
// design doc's approach (a): the data-fetch + problem-build breakdown below is produced by calling
// the SAME lower-level pieces `generate()` calls, in the same sequence, from this script (a
// read-only "shadow" run, safe to duplicate) -- while `solve` and `persist` are timed on the ONE
// real `generate()` call by injecting a wrapped `solve` function through the service's existing,
// already-used-by-its-own-tests constructor seam (`SolveFn`, `rosterGenerationService.ts`'s 2nd
// constructor param). This is exact, not an approximation, for solve/persist: `preSolveMs` below
// is measured as (real solve-start timestamp) - (real generate()-call-start timestamp), and
// `persistMs` as (real generate()-call-end timestamp) - (real solve-end timestamp) -- both derived
// entirely from the one real, unduplicated `generate()` invocation. The separate shadow run only
// exists to further split that same "pre-solve" span into its own data-fetch / problem-build
// numbers for the report; it does not touch the DB with writes and never runs `generate()` itself.
// ---------------------------------------------------------------------------------------------

interface ShadowFetchResult {
  readonly dataFetchMs: number;
  readonly problemBuildMs: number;
  readonly workerCandidatePoolCount: number;
  readonly requirementRowCount: number;
}

/** Re-implements `RosterGenerationService.generate()`'s eligibility query + data-fetch +
 * `buildProblem` call, verbatim in sequence, purely to time each piece from outside -- see the
 * section doc comment above. Read-only; never called anywhere except this benchmark. */
async function shadowDataFetchAndBuild(
  prisma: PrismaClient,
  companyId: number,
  month: string,
): Promise<ShadowFetchResult> {
  const fetchStart = performance.now();

  const latestWorkerSyncTask = await prisma.importTask.findFirst({
    where: { companyId, kind: 'WORKER_SYNC', status: 'COMPLETED' },
    orderBy: { finishedAt: 'desc' },
  });

  const [activeWorkers, requirements] = await Promise.all([
    prisma.worker.findMany({
      where: {
        companyId,
        status: 'ACTIVE',
        OR: [{ lastImportTaskId: null }, { lastImportTaskId: latestWorkerSyncTask?.id ?? -1 }],
      },
      include: { contract: true },
    }),
    prisma.staffingRequirement.findMany({ where: { companyId } }),
  ]);

  const workersWithContract = activeWorkers.filter(
    (w): w is typeof w & { contract: NonNullable<typeof w.contract> } => w.contract !== null,
  );
  const workerIds = workersWithContract.map((w) => w.id);

  const days = monthDays(month);
  const firstDay = days[0];
  const lastDay = days[days.length - 1];
  let availabilityRows: EngineAvailabilityRow[] = [];
  if (workerIds.length > 0 && firstDay !== undefined && lastDay !== undefined) {
    const rows = await prisma.workerAvailability.findMany({
      where: {
        workerId: { in: workerIds },
        date: { gte: new Date(`${firstDay}T00:00:00.000Z`), lte: new Date(`${lastDay}T00:00:00.000Z`) },
      },
    });
    availabilityRows = rows.map((row) => ({
      workerId: row.workerId,
      date: row.date.toISOString().slice(0, 10),
      shifts: row.shifts.split('') as ShiftType[],
    }));
  }

  const fetchEnd = performance.now();

  buildProblem({
    month,
    workers: workersWithContract.map((w) => ({
      id: w.id,
      role: w.role,
      minMonthlyHours: w.contract.minMonthlyHours,
      maxMonthlyHours: w.contract.maxMonthlyHours,
    })),
    requirements: requirements.map((r) => ({ role: r.role, shift: r.shift, requiredCount: r.requiredCount })),
    availability: availabilityRows,
  });

  const buildEnd = performance.now();

  return {
    dataFetchMs: fetchEnd - fetchStart,
    problemBuildMs: buildEnd - fetchEnd,
    workerCandidatePoolCount: workersWithContract.length,
    requirementRowCount: requirements.length,
  };
}

interface RosterGenerationTiming {
  readonly dataFetchMs: number;
  readonly problemBuildMs: number;
  readonly preSolveMs: number;
  readonly solveMs: number | null;
  readonly persistMs: number | null;
  readonly totalMs: number;
  readonly workerCandidatePoolCount: number;
  readonly requirementRowCount: number;
  readonly assignmentsCount: number | null;
  readonly alertCount: number | null;
  readonly error: string | null;
  readonly solveTimedOutOrKilled: boolean;
}

async function timeRosterGeneration(
  prisma: PrismaClient,
  companyId: number,
  month: string,
  solverAvailable: boolean,
): Promise<RosterGenerationTiming | null> {
  if (!solverAvailable) {
    return null;
  }

  const shadow = await shadowDataFetchAndBuild(prisma, companyId, month);

  let solveStart = 0;
  let solveEnd = 0;
  let solveTimedOutOrKilled = false;

  const wrappedSolve: SolveFn = async (problem, options?: RunSolverOptions) => {
    solveStart = performance.now();
    try {
      const solution = await runSolver(problem, options);
      solveEnd = performance.now();
      return solution;
    } catch (err) {
      solveEnd = performance.now();
      const message = err instanceof Error ? err.message : String(err);
      if (/signal|timeout|timed out/i.test(message)) {
        solveTimedOutOrKilled = true;
      }
      throw err;
    }
  };

  const service = new RosterGenerationService(prisma, wrappedSolve, { pythonExecutable: VENV_PYTHON });

  const generateStart = performance.now();
  let assignmentsCount: number | null = null;
  let alertCount: number | null = null;
  let error: string | null = null;
  try {
    const result = await service.generate(companyId, month);
    alertCount = result.alertCount;
    const shifts = await prisma.shiftWorker.count({ where: { shift: { rosterId: result.rosterId } } });
    assignmentsCount = shifts;
  } catch (err) {
    error = err instanceof Error ? err.message : String(err);
  }
  const generateEnd = performance.now();

  const solveMs = solveStart > 0 && solveEnd > 0 ? solveEnd - solveStart : null;
  const preSolveMs = solveStart > 0 ? solveStart - generateStart : generateEnd - generateStart;
  const persistMs = solveEnd > 0 && error === null ? generateEnd - solveEnd : null;

  return {
    dataFetchMs: shadow.dataFetchMs,
    problemBuildMs: shadow.problemBuildMs,
    preSolveMs,
    solveMs,
    persistMs,
    totalMs: generateEnd - generateStart,
    workerCandidatePoolCount: shadow.workerCandidatePoolCount,
    requirementRowCount: shadow.requirementRowCount,
    assignmentsCount,
    alertCount,
    error,
    solveTimedOutOrKilled,
  };
}

// ---------------------------------------------------------------------------------------------
// Per-tier orchestration
// ---------------------------------------------------------------------------------------------

interface TierResult {
  readonly tier: number;
  readonly companyId: number;
  readonly companyName: string;
  readonly csvImport: {
    readonly totalRows: number;
    readonly inserted: number;
    readonly updated: number;
    readonly failed: number;
    readonly rowProcessingMs: number;
    readonly rowsPerSec: number;
  };
  readonly requirementsSetup: { readonly ms: number; readonly roleCounts: Record<Role, number> };
  readonly availabilitySetup: { readonly ms: number; readonly rowsCreated: number };
  readonly rosterGeneration: RosterGenerationTiming | null;
  readonly pass: boolean | null;
  readonly passReason: string;
}

async function runTier(
  prisma: PrismaClient,
  boss: Awaited<ReturnType<typeof createBoss>>,
  tier: number,
  solverAvailable: boolean,
): Promise<TierResult> {
  console.log(`\n=== Tier ${tier} workers ===`);

  const companyName = `LoadTest Scale Tier ${tier} - ${Date.now()}`;
  const company = await prisma.company.create({ data: { name: companyName } });
  console.log(`  created company ${company.id} (${companyName})`);

  const csvImportService = new CsvImportService(prisma, boss);
  const records = buildSyntheticWorkerRecords(tier);
  const csvText = serializeWorkersCsv(records);

  console.log(`  importing ${tier} synthetic workers (in-process CsvImportService.importCsv)...`);
  const importStart = performance.now();
  const importResult = await csvImportService.importCsv(csvText, company.id);
  const importEnd = performance.now();
  const rowProcessingMs = importEnd - importStart;
  const rowsPerSec = importResult.totalRows / (rowProcessingMs / 1000);
  console.log(
    `  import done: ${importResult.inserted} inserted, ${importResult.updated} updated, ` +
      `${importResult.failed} failed in ${rowProcessingMs.toFixed(0)}ms (${rowsPerSec.toFixed(1)} rows/sec)`,
  );
  if (importResult.failed > 0) {
    console.warn(`  WARNING: ${importResult.failed} row(s) failed to import -- first error:`, importResult.errors[0]);
  }

  const reqStart = performance.now();
  const roleCounts = await scaleStaffingRequirements(prisma, company.id);
  const reqEnd = performance.now();
  console.log(`  staffing requirements scaled (utilization ratio ${UTILIZATION_RATIO}): ${JSON.stringify(roleCounts)}`);

  let availabilitySetupMs = 0;
  let availabilityRowsCreated = 0;
  if (solverAvailable) {
    const availStart = performance.now();
    availabilityRowsCreated = await seedAvailability(prisma, company.id, TARGET_MONTH);
    availabilitySetupMs = performance.now() - availStart;
    console.log(
      `  seeded ${availabilityRowsCreated} availability rows for ${TARGET_MONTH} in ${availabilitySetupMs.toFixed(0)}ms`,
    );
  } else {
    console.warn('  solver/.venv not found -- skipping availability seeding and roster-generation stage entirely.');
  }

  console.log('  generating roster (in-process RosterGenerationService.generate, real Python solver subprocess)...');
  const rosterGeneration = await timeRosterGeneration(prisma, company.id, TARGET_MONTH, solverAvailable);
  if (rosterGeneration) {
    if (rosterGeneration.error) {
      console.warn(`  roster generation FAILED: ${rosterGeneration.error}`);
    } else {
      console.log(
        `  roster generation done: data-fetch ${rosterGeneration.dataFetchMs.toFixed(0)}ms, ` +
          `problem-build ${rosterGeneration.problemBuildMs.toFixed(0)}ms, ` +
          `solve ${rosterGeneration.solveMs?.toFixed(0) ?? 'n/a'}ms, ` +
          `persist ${rosterGeneration.persistMs?.toFixed(0) ?? 'n/a'}ms, ` +
          `total ${rosterGeneration.totalMs.toFixed(0)}ms, ` +
          `${rosterGeneration.assignmentsCount ?? 0} assignments, ${rosterGeneration.alertCount ?? 0} alerts`,
      );
    }
  }

  let pass: boolean | null = null;
  let passReason = 'not evaluated';
  if (rosterGeneration) {
    if (rosterGeneration.error) {
      pass = false;
      passReason = rosterGeneration.solveTimedOutOrKilled
        ? `solve timed out / was killed: ${rosterGeneration.error}`
        : `roster generation errored: ${rosterGeneration.error}`;
    } else if (rosterGeneration.solveMs === null) {
      pass = false;
      passReason = 'solve stage never ran (unexpected)';
    } else if (rosterGeneration.solveMs > SOLVE_REASONABLE_BOUND_MS) {
      pass = false;
      passReason = `solve took ${rosterGeneration.solveMs.toFixed(0)}ms, exceeding the ${SOLVE_REASONABLE_BOUND_MS}ms bound`;
    } else {
      pass = true;
      passReason = `solve completed in ${rosterGeneration.solveMs.toFixed(0)}ms, within the ${SOLVE_REASONABLE_BOUND_MS}ms bound`;
    }
  } else {
    passReason = 'solver unavailable (solver/.venv missing) -- roster-generation stage skipped entirely';
  }

  return {
    tier,
    companyId: company.id,
    companyName,
    csvImport: {
      totalRows: importResult.totalRows,
      inserted: importResult.inserted,
      updated: importResult.updated,
      failed: importResult.failed,
      rowProcessingMs,
      rowsPerSec,
    },
    requirementsSetup: { ms: reqEnd - reqStart, roleCounts },
    availabilitySetup: { ms: availabilitySetupMs, rowsCreated: availabilityRowsCreated },
    rosterGeneration,
    pass,
    passReason,
  };
}

// ---------------------------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------------------------

function printConsoleTable(results: readonly TierResult[]): void {
  console.log('\n\n=== Scale-tier benchmark summary ===\n');
  console.table(
    results.map((r) => ({
      tier: r.tier,
      'import rows/sec': r.csvImport.rowsPerSec.toFixed(1),
      'import ms': r.csvImport.rowProcessingMs.toFixed(0),
      'data-fetch ms': r.rosterGeneration?.dataFetchMs.toFixed(0) ?? 'n/a',
      'problem-build ms': r.rosterGeneration?.problemBuildMs.toFixed(0) ?? 'n/a',
      'solve ms': r.rosterGeneration?.solveMs?.toFixed(0) ?? 'n/a',
      'persist ms': r.rosterGeneration?.persistMs?.toFixed(0) ?? 'n/a',
      'generate total ms': r.rosterGeneration?.totalMs.toFixed(0) ?? 'n/a',
      pass: r.pass === null ? 'n/a' : r.pass ? 'PASS' : 'FAIL',
    })),
  );
  for (const r of results) {
    console.log(`Tier ${r.tier}: ${r.passReason}`);
  }
}

async function writeArtifacts(results: readonly TierResult[]): Promise<void> {
  await mkdir(RESULTS_DIR, { recursive: true });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const jsonPath = path.join(RESULTS_DIR, `scale-tiers-${timestamp}.json`);
  const mdPath = path.join(RESULTS_DIR, `scale-tiers-${timestamp}.md`);

  await writeFile(
    jsonPath,
    JSON.stringify(
      { generatedAt: new Date().toISOString(), utilizationRatio: UTILIZATION_RATIO, targetMonth: TARGET_MONTH, results },
      null,
      2,
    ),
    'utf8',
  );

  const mdLines: string[] = [
    `# Scale-tier benchmark — ${new Date().toISOString()}`,
    '',
    `Utilization ratio: ${UTILIZATION_RATIO}. Target month: ${TARGET_MONTH}. Solve reasonable bound: ${SOLVE_REASONABLE_BOUND_MS}ms.`,
    '',
    '| Tier | Import rows/sec | Import ms | Data-fetch ms | Problem-build ms | Solve ms | Persist ms | Generate total ms | Pass |',
    '|---|---|---|---|---|---|---|---|---|',
  ];
  for (const r of results) {
    mdLines.push(
      `| ${r.tier} | ${r.csvImport.rowsPerSec.toFixed(1)} | ${r.csvImport.rowProcessingMs.toFixed(0)} | ` +
        `${r.rosterGeneration?.dataFetchMs.toFixed(0) ?? 'n/a'} | ${r.rosterGeneration?.problemBuildMs.toFixed(0) ?? 'n/a'} | ` +
        `${r.rosterGeneration?.solveMs?.toFixed(0) ?? 'n/a'} | ${r.rosterGeneration?.persistMs?.toFixed(0) ?? 'n/a'} | ` +
        `${r.rosterGeneration?.totalMs.toFixed(0) ?? 'n/a'} | ${r.pass === null ? 'n/a' : r.pass ? 'PASS' : 'FAIL'} |`,
    );
  }
  mdLines.push('', '## Notes', '');
  for (const r of results) {
    mdLines.push(`- Tier ${r.tier}: ${r.passReason}`);
  }
  await writeFile(mdPath, mdLines.join('\n') + '\n', 'utf8');

  console.log(`\nArtifacts written:\n  ${jsonPath}\n  ${mdPath}`);
}

// ---------------------------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------------------------

async function main(): Promise<void> {
  const cliTiers = process.argv.slice(2).map(Number).filter((n) => Number.isFinite(n) && n > 0);
  const tiers = [...(cliTiers.length > 0 ? cliTiers : ALL_TIERS)].sort((a, b) => a - b);

  const solverAvailable = existsSync(VENV_PYTHON);
  if (!solverAvailable) {
    console.warn(
      `\nBLOCKER: ${VENV_PYTHON} not found. Roster-generation stage (data-fetch/problem-build/solve/persist) ` +
        'will be skipped for every tier -- only CSV-import numbers will be real. See solver/README.md to set up ' +
        'the venv (`cd solver && python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt`).\n',
    );
  }

  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is not set -- copy .env.example to .env at the repo root (see docker-compose.dev.yml).');
  }

  const prisma = createPrismaClient(databaseUrl);
  const boss = createBoss(databaseUrl);

  const results: TierResult[] = [];
  try {
    for (const tier of tiers) {
      const result = await runTier(prisma, boss, tier, solverAvailable);
      results.push(result);
      // Write partial results after every tier -- if a later (larger) tier hangs or the process is
      // killed, the smaller tiers' real numbers are not lost.
      await writeArtifacts(results);
    }
  } finally {
    printConsoleTable(results);
    await prisma.$disconnect();
    await boss.stop({ graceful: false, close: true });
  }
}

main().catch((err: unknown) => {
  console.error('scaleTiers.ts failed:', err);
  process.exitCode = 1;
});
